#!/bin/bash

# pm2ログディレクトリに移動
cd ~/.pm2/logs

# logファイルを数字順にソートしてループ
for log in $(ls -v 3-initiatorStartPM2-error.log*); do
    # 拡張子が.gzのlogファイルをunzipする
    if [[ "$log" == *.gz ]]; then
        gunzip "$log"
    fi
done

# logファイルを数字順にソートしてループ
for log in $(ls -v 3-initiatorStartPM2-error.log*); do
    # 区切り線を出力
    echo
    echo "--------------------------------------------------------------------------------"
    echo "                                     $log"
    echo "--------------------------------------------------------------------------------"

    # grepコマンドを使って抽出したテキストを出力
    grep -E 'HTTP status | ERROR | error' "$log"
done >"3-initiatorStartPM2-error-combined.log"

less 3-initiatorStartPM2-error-combined.log

# 2..10までを圧縮
# ./assyuku.sh

less 3-initiatorStartPM2-error-combined.log

# 3-initiatorStartPM2-error.log
# 3-initiatorStartPM2-error.log.1
# 3-initiatorStartPM2-error.log.2
# 3-initiatorStartPM2-error.log.3
# 3-initiatorStartPM2-error.log.4
# 3-initiatorStartPM2-error.log.5
# 3-initiatorStartPM2-error.log.6
# 3-initiatorStartPM2-error.log.7
# 3-initiatorStartPM2-error.log.8
# 3-initiatorStartPM2-error.log.9
# 3-initiatorStartPM2-error.log.10
