#!/bin/bash

log_files=($(ls | grep '\.log$'))
num_log_files=${#log_files[@]}
page_size=10
page_num=0

# show log files
function show_log_files() {
    start=$((page_size * page_num))
    end=$((start + page_size - 1))

    if [[ $end -gt $((num_log_files - 1)) ]]; then
        end=$((num_log_files - 1))
    fi

    echo "表示したいファイルを選択してください。"
    echo
    for i in $(seq $start $end); do
        echo "$((i + 1)). ${log_files[i]}"
    done
    echo
}

while true; do
    show_log_files

    if [[ $page_num -eq $((num_log_files / page_size)) ]]; then
        read -p "これが最終ページです。番号を選択してください (qで終了): " choice
    else
        read -p "次のページを見るには「n 」を押してください (qで終了): " choice
    fi

    if [[ $choice == "q" ]]; then
        break
    elif [[ $choice =~ ^[0-9]+$ ]]; then
        selected_index=$((choice - 1))
        if [[ $selected_index -ge $num_log_files ]]; then
            echo
            echo "不正な番号です"
            echo
        else
            selected_log_file=${log_files[selected_index]}
            echo
            echo "$((selected_index + 1)). $selected_log_file をまとめて表示します。よろしいですか？"
            echo
            break
        fi
    elif [[ $choice == "n" ]]; then
        page_num=$((page_num + 1))
    else
        echo "不正な入力です"
    fi
done
